language: cpp
compiler:
    - clang
install:
    - sudo add-apt-repository --yes ppa:kalakris/cmake
    - sudo apt-get update -qq
    - sudo apt-get install cmake
    - sudo apt-get install xorg-dev
    - sudo apt-get install libglu1-mesa-dev
    - sudo apt-get install libassimp-dev
before_script:
     - mkdir build
     - cd build
     - cmake ..
script: make
